python:
  - 3.10
  - 3.11
  - 3.12
c_compiler:  # [win]
  - vs2022   # [win]
target_platform:  # [win]
  - win-64        # [win]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "13.3"                 # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "13.3"                 # [osx and x86_64]
