{% set name = "pyarts" %}
{% set version = "2.5.4" %}
{% set dev_url = "https://github.com/atmtools/arts" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: {{ dev_url }}/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: e838680fa5e4e3fc9beae3f48b657ab7f6300dd2701bbf5e4c58d264edae64ab
  git_url: {{ dev_url }}.git
  git_depth: 1

build:
  skip: True  # [win]
  number: 1

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.20
    - make                               # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    # - {{ cdt('mesa-libegl-devel') }}  # [linux]
    # - {{ cdt('mesa-dri-drivers') }}  # [linux]
    # - {{ cdt('libselinux') }}        # [linux]
    # - {{ cdt('libxdamage') }}        # [linux]
    # - {{ cdt('libxfixes') }}         # [linux]
    # - {{ cdt('libxxf86vm') }}        # [linux]
  host:
    - python {{ python }}
    - docutils
    - glew
    - glfw
    - lark-parser
    - libgomp         # [linux]
    - libopenblas
    - matplotlib
    - netcdf4
    - numpy >=1.20
    - pip
    - pytest
    - pytest-runner
    - scipy
    - xarray
    - zlib
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}  # [osx and x86_64]
    - python
    - glew
    - glfw
    - libopenblas
    - matplotlib
    - netcdf4
    - numpy
    - scipy
    - xarray
    - zlib


about:
  home: https://github.com/atmtools/arts
  summary: 'The Atmospheric Radiative Transfer Simulator'
  description: |
      Python interface to ARTS
  license: GPL-2.0-only
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file:
    - LICENSE.txt
    - vendor-licenses/
  # The doc_url and dev_url are optional.
  doc_url: https://atmtools.github.io/arts-docs-master/
  dev_url: https://github.com/atmtools/arts

extra:
  recipe-maintainers:
    - olemke
